fix(autosubmit): Add -u to push
Otherwise for the `git-obs pr create` we get:

```
    Creating a pull request ...
     * Local git: branch: leap-16.0, commit: 95ea17040
     * Source: pool/openQA, branch: leap-16.0, commit: ec75c2988
     * Target: pool/openQA, branch: leap-16.0, commit: ec75c2988

    ERROR: Local commit doesn't correspond with the latest commit in the remote
    source branch. Did you forget to push your changes with 'git push'?
```

So it is detecting the source wrong.

A followup fix for `git-obs pr create` should also switch from the deprecated
`--target-branch` to `--target` and `--source`.

Issue: https://progress.opensuse.org/issues/205521